on:
  push:
  pull_request:
  release:
    types:
      - prereleased
      - released

jobs:
  ubuntu-build:
    strategy:
      matrix:
        include:
          - name: Ubuntu 24.04 gcc x86_64
            filename: ubuntu-24.04-x86_64
            docker: ubuntu-24.04
            compiler: gcc
            arch: x86_64
            publish_artifact: true
            deploy_release: true
    name: ${{matrix.name}}
    permissions:
      contents: write # Needed to upload to releases
    runs-on: ubuntu-latest # https://github.com/actions/runner-images/tree/main/images/ubuntu
    steps:
      - name: Git Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          path: src
      - name: Git Submodule
        run: set -eu && git -C src submodule update --init --recursive
      - name: Docker Build
        run: set -eu && docker build --build-arg UID=$UID -f src/docker/${{matrix.docker}}/Dockerfile -t ubuntu src
      - name: Export Environment
        run: |
          set -eu

          echo WZ_DISTRIBUTOR=${GITHUB_REPOSITORY%/*} >> $GITHUB_ENV

          WZ_NAME_SUFFIX=
          WZ_OUTPUT_NAME_SUFFIX=
          if [[ $GITHUB_REF_TYPE != tag ]]; then
            suffix=${GITHUB_HEAD_REF-$GITHUB_REF_NAME}
            suffix=${suffix////_}
            suffix=${suffix//-/_}
            suffix=$(sed 's/[^a-zA-Z0-9\.]/_/g' <<< "$suffix")
            WZ_NAME_SUFFIX=" ($suffix)"
            WZ_OUTPUT_NAME_SUFFIX=_$suffix
          fi
          echo WZ_NAME_SUFFIX=$WZ_NAME_SUFFIX >> $GITHUB_ENV
          echo WZ_OUTPUT_NAME_SUFFIX=$WZ_OUTPUT_NAME_SUFFIX >> $GITHUB_ENV

          case ${{matrix.compiler}} in
            (gcc)
              echo CC=/usr/bin/gcc
              echo CXX=/usr/bin/g++
            ;;
            (clang)
              echo CC=/usr/bin/clang
              echo CXX=/usr/bin/clang++
            ;;
          esac >> $GITHUB_ENV
      - name: CMake Configure
        run: |
          set -eu
          echo "::add-matcher::$GITHUB_WORKSPACE/src/.github/log-matchers/cmake.json"
          docker run --rm \
            --env CI \
            --env GITHUB_ACTIONS --env GITHUB_REPOSITORY --env GITHUB_WORKFLOW --env GITHUB_WORKSPACE \
            --env GITHUB_SHA --env GITHUB_REF --env GITHUB_HEAD_REF --env GITHUB_BASE_REF \
            --env CC --env CXX \
            --volume $GITHUB_WORKSPACE:$GITHUB_WORKSPACE \
            ubuntu \
              cmake \
                -G Ninja \
                -S $GITHUB_WORKSPACE/src \
                -B $GITHUB_WORKSPACE/build \
                -D CMAKE_BUILD_TYPE=Release \
                -D WZ_DISTRIBUTOR="$WZ_DISTRIBUTOR" \
                -D WZ_NAME_SUFFIX="$WZ_NAME_SUFFIX" \
                -D WZ_OUTPUT_NAME_SUFFIX="$WZ_OUTPUT_NAME_SUFFIX" \
                -D WZ_ENABLE_WARNINGS=0 \
                -D ENABLE_DISCORD=0 \
                -D ENABLE_GNS_NETWORK_BACKEND=0
          echo '::remove-matcher owner=cmake::'
      - name: CMake Build
        run: |
          set -eu
          echo "::add-matcher::$GITHUB_WORKSPACE/src/.github/log-matchers/${{matrix.compiler}}.json"
          docker run --rm \
            --env CI \
            --env GITHUB_ACTIONS --env GITHUB_REPOSITORY --env GITHUB_WORKFLOW --env GITHUB_WORKSPACE \
            --env GITHUB_SHA --env GITHUB_REF --env GITHUB_HEAD_REF --env GITHUB_BASE_REF \
            --env CC --env CXX \
            --volume $GITHUB_WORKSPACE:$GITHUB_WORKSPACE \
            ubuntu \
              cmake --build $GITHUB_WORKSPACE/build
          echo '::remove-matcher owner=${{matrix.compiler}}::'
      - name: CPack Debian
        run: |
          set -eu
          docker run --rm \
            --env CI \
            --env GITHUB_ACTIONS --env GITHUB_REPOSITORY --env GITHUB_WORKFLOW --env GITHUB_WORKSPACE \
            --env GITHUB_SHA --env GITHUB_REF --env GITHUB_HEAD_REF --env GITHUB_BASE_REF \
            --volume $GITHUB_WORKSPACE:$GITHUB_WORKSPACE \
            --workdir $GITHUB_WORKSPACE/build \
            ubuntu \
              cpack \
                --config ./CPackConfig.cmake \
                -G DEB \
                -D CPACK_DEBIAN_PACKAGE_MAINTAINER="$WZ_DISTRIBUTOR" \
                -D CPACK_DEB_COMPONENT_INSTALL=ON \
                -D CPACK_COMPONENTS_GROUPING=ALL_COMPONENTS_IN_ONE \
                -D CPACK_DEBIAN_PACKAGE_NAME=warzone2100$WZ_OUTPUT_NAME_SUFFIX \
                -D CPACK_DEBIAN_FILE_NAME=warzone2100-${{matrix.filename}}.deb
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        if: success() && github.event_name != 'release' && matrix.publish_artifact
        with:
          name: warzone2100-${{matrix.filename}}_deb
          archive: false # do not zip
          path: ${{github.workspace}}/build/warzone2100-${{matrix.filename}}.deb
          if-no-files-found: error
      - name: Upload Release
        if: success() && github.event_name == 'release' && matrix.deploy_release
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GH_REPO: ${{github.repository}}
        run: set -eu && gh release upload "$GITHUB_REF_NAME" build/warzone2100-${{matrix.filename}}.deb
