on:
  push:
  pull_request:
  release:
    types:
      - prereleased
      - released

jobs:
  windows-build:
    strategy:
      matrix:
        include:
          - name: Windows mingw ucrt clang x86_64
            filename: windows-x86_64
            compiler: clang
            arch: x86_64
            publish_artifact: true
            deploy_release: true
          #- name: Windows mingw ucrt clang arm64
          #  filename: windows-arm64
          #  compiler: clang
          #  arch: arm64
          #  publish_artifact: true
          #  deploy_release: true
    name: ${{matrix.name}}
    permissions:
      contents: write # Needed to upload to releases
    runs-on: windows-2022 # https://github.com/actions/runner-images/tree/main/images/windows
    steps:
    - name: Dump Environment (pwsh)
      shell: pwsh
      run: echo $Env:PATH
    - name: Dump Environment (bash)
      shell: bash
      run: |
        set -eu
        uname -a
        mount
        echo ===============================================================================
        env | sort
        echo ===============================================================================
        IFS=: read -ra path <<< "$PATH"
        printf 'PATH=%s\n' "${path[@]}"
        for p in "${path[@]}"; do
          echo ===============================================================================
          echo $p
          ls -la "$p" || true
        done
    - name: Remove Strawberry Perl from PATH # workaround for https://github.com/actions/runner-images/issues/5459
      shell: pwsh
      run: |
        $Env:PATH = ($Env:PATH -split ';' | ?{ $_ -notmatch '\\Strawberry\\c\\bin$' }) -join ';'
        echo "PATH=$Env:PATH" | Out-File -FilePath $Env:GITHUB_ENV -Append
    - name: Dump Environment (pwsh)
      shell: pwsh
      run: echo $Env:PATH
    - name: Git Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        path: src
    - name: Git Submodule
      shell: bash
      run: git -C $GITHUB_WORKSPACE/src submodule update --init --recursive
    - name: Export Environment (bash)
      shell: bash
      run: |
        set -eu
        echo WZ_DISTRIBUTOR=${GITHUB_REPOSITORY%/*} >> $GITHUB_ENV
        echo WZ_SUFFIX=$(sed 's,[^a-zA-Z0-9._-],-,g' <<< "${GITHUB_HEAD_REF-$GITHUB_REF_NAME}") >> $GITHUB_ENV
        echo VCPKG_DEFAULT_HOST_TRIPLET=x64-mingw-static >> $GITHUB_ENV
        case ${{matrix.arch}} in
          (x86_64)
            echo VCPKG_DEFAULT_TRIPLET=x64-mingw-dynamic
            echo WZ_MINGW_PKG_PREFIX=x86_64-w64-mingw32
          ;;
          (arm64)
            echo VCPKG_DEFAULT_TRIPLET=arm64-mingw-dynamic
            echo WZ_MINGW_PKG_PREFIX=aarch64-w64-mingw32
          ;;
        esac >> $GITHUB_ENV
    - name: Export Environment (pwsh)
      shell: pwsh
      run: |
        $WZ_VCPKG_BINARY_SOURCES_DIR = "$Env:GITHUB_WORKSPACE\vcpkg_cache"
        echo "WZ_VCPKG_BINARY_SOURCES_DIR=$WZ_VCPKG_BINARY_SOURCES_DIR" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        echo "VCPKG_BINARY_SOURCES=clear;files,$WZ_VCPKG_BINARY_SOURCES_DIR,readwrite" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

        echo "WZ_POWERSHELL_PATH=$((Get-Command powershell.exe).Path)" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        echo "WZ_GIT_PATH=$(Split-Path -Path ((Get-Command git.exe).Path))" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        echo "WZ_CMAKE_PATH=$(Split-Path -Path ((Get-Command cmake.exe).Path))" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
    - name: Setup AsciiDoctor
      shell: pwsh
      run: |
        gem install asciidoctor -v 2.0.23 --no-document | Out-Null
        $AsciidoctorBat = (Get-Command asciidoctor.bat).Path
        $AsciidoctorBatPath = Split-Path -Path "$AsciidoctorBat"
        echo "WZ_ASCIIDOCTOR_PATH=$AsciidoctorBatPath" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
    - name: Setup GetText
      shell: pwsh
      run: |
        $Env:PATH = "C:\msys64\mingw64\bin;C:\msys64\usr\bin;$Env:PATH"

        pacman --noconfirm -S --needed gettext
        if ($LastExitCode -ne 0) {
            throw "Failed to install gettext with exit code: $LastExitCode"
        }

        $WZ_MSGMERGE_PATH = Split-Path -Path ((Get-Command msgmerge.exe).Path)
        echo "WZ_MSGMERGE_PATH=$WZ_MSGMERGE_PATH" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

        $WZ_MSGFMT_PATH = Split-Path -Path ((Get-Command msgfmt.exe).Path)
        echo "WZ_MSGFMT_PATH=$WZ_MSGFMT_PATH" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
    - name: Setup Vulkan SDK
      shell: pwsh
      run: |
        Start-Sleep -Milliseconds 1 # See: https://stackoverflow.com/a/49859001
        $VerbosePreference = "Continue"
        . .\src\.ci\powershell\request.ps1

        $VULKAN_DL_URL = "https://sdk.lunarg.com/sdk/download/1.4.328.1/windows/vulkansdk-windows-X64-1.4.328.1.exe?Human=true"
        $VULKAN_DL_SHA256 = "a8675df6d538079c2a719a9373994948091db785b48f142e024254e76348d16c"

        $VK_DL_BASEDIR = "$Env:GITHUB_WORKSPACE\dl"
        $VK_DL_PATH = "$VK_DL_BASEDIR\vulkan.exe"
        New-Item -ItemType Directory -Force -Path "$VK_DL_BASEDIR"

        $req = Req -Params @{ 'Method'='GET';'Uri'="$VULKAN_DL_URL";'OutFile'="$VK_DL_PATH" } -Retries 3 -SecondsDelay 10 -ExpectedHash "$VULKAN_DL_SHA256" -Algorithm SHA256

        Start-Process "$VK_DL_PATH" -ArgumentList "--accept-licenses","--default-answer","--confirm-command","install" -Wait

        echo "VULKAN_SDK=$([Environment]::GetEnvironmentVariables("Machine")["VULKAN_SDK"])" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
    - name: Setup Ninja
      shell: pwsh
      run: |
        Start-Sleep -Milliseconds 1 # See: https://stackoverflow.com/a/49859001
        $VerbosePreference = "Continue"
        . .\src\.ci\powershell\request.ps1

        $NINJA_DL_URL = "https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-win.zip"
        $NINJA_DL_SHA512 = "55d3d891e8fc6c8ad7f92e172125319896761e57c5125944613d9bbfa5b9374387e9fc1468ad5bcb31464f43fb1c455ea251343942595f42955dc67090aa12ee"

        $NINJA_DL_BASEDIR = "$Env:GITHUB_WORKSPACE\dl"
        $NINJA_DL_PATH = "$NINJA_DL_BASEDIR\ninja-win.zip"
        if (!(Test-Path -Path "$NINJA_DL_BASEDIR")) { New-Item -ItemType Directory -Force -Path "$NINJA_DL_BASEDIR" }

        $req = Req -Params @{ 'Method'='GET';'Uri'="$NINJA_DL_URL";'OutFile'="$NINJA_DL_PATH" } -Retries 3 -SecondsDelay 10 -ExpectedHash "$NINJA_DL_SHA512" -Algorithm SHA512

        $WZ_NINJA_INSTALL_PATH = "$Env:GITHUB_WORKSPACE\buildtools\ninja"
        New-Item -ItemType Directory -Force -Path $WZ_NINJA_INSTALL_PATH
        Expand-Archive -LiteralPath $NINJA_DL_PATH -DestinationPath $WZ_NINJA_INSTALL_PATH

        echo "WZ_NINJA_INSTALL_PATH=$WZ_NINJA_INSTALL_PATH" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
    - name: Setup LLVM-MinGW
      shell: pwsh
      run: |
        Start-Sleep -Milliseconds 1 # See: https://stackoverflow.com/a/49859001
        $VerbosePreference = "Continue"
        . .\src\.ci\powershell\request.ps1

        $LLVM_MINGW_RELEASE = "20250709";
        $LLVM_MINGW_PKG = "llvm-mingw-$LLVM_MINGW_RELEASE-ucrt-x86_64"
        $LLVM_MINGW_DL_URL = "https://github.com/mstorsjo/llvm-mingw/releases/download/$LLVM_MINGW_RELEASE/$LLVM_MINGW_PKG.zip"
        $LLVM_MINGW_DL_SHA512 = "e080a8928d7ae6263a54d506949421ca03e269a1829f7fdaae53accb9b060a404ec1e6c32eb8b08e051769edd943437635e0dd8beb16ed06b9b04e9423609714"

        $LLVM_MINGW_DL_BASEDIR = "$Env:GITHUB_WORKSPACE\dl"
        $LLVM_MINGW_DL_PATH = "$LLVM_MINGW_DL_BASEDIR\llvm-mingw.zip"
        if (!(Test-Path -Path "$LLVM_MINGW_DL_BASEDIR")) { New-Item -ItemType Directory -Force -Path "$LLVM_MINGW_DL_BASEDIR" }

        $req = Req -Params @{ 'Method'='GET';'Uri'="$LLVM_MINGW_DL_URL";'OutFile'="$LLVM_MINGW_DL_PATH" } -Retries 3 -SecondsDelay 10 -ExpectedHash "$LLVM_MINGW_DL_SHA512" -Algorithm SHA512

        $LLVM_MINGW_INSTALL_PATH = "$Env:GITHUB_WORKSPACE\buildtools\llvm-mingw"
        New-Item -ItemType Directory -Force -Path "$LLVM_MINGW_INSTALL_PATH"
        Expand-Archive -LiteralPath "$LLVM_MINGW_DL_PATH" -DestinationPath "$LLVM_MINGW_INSTALL_PATH"

        # Export the LLVM-mingw install path
        $LLVM_MINGW_INSTALL_PATH = "$LLVM_MINGW_INSTALL_PATH\$LLVM_MINGW_PKG"
        echo "LLVM_MINGW_INSTALL_PATH=$LLVM_MINGW_INSTALL_PATH" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

        # Add bin path to the system PATH
        echo "$LLVM_MINGW_INSTALL_PATH\bin" | Out-File -FilePath $Env:GITHUB_PATH -Encoding utf8 -Append
    - name: MinGW Environment
      shell: pwsh
      run: |
        # $Env:PATH = "C:\msys64\ucrt64\bin;C:\msys64\usr\bin;$Env:PATH"
        $WZ_MINGW_DIST_PATH = "$Env:LLVM_MINGW_INSTALL_PATH\$Env:WZ_MINGW_PKG_PREFIX\bin"
        echo "WZ_MINGW_DIST_PATH=$WZ_MINGW_DIST_PATH" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        $POWERSHELL_FOLDER = Split-Path -Path "$Env:WZ_POWERSHELL_PATH"
        $WZ_MINGW_ENV_PATH = "$Env:LLVM_MINGW_INSTALL_PATH\bin;$Env:WZ_GIT_PATH;$POWERSHELL_FOLDER;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;$Env:WZ_NINJA_INSTALL_PATH;$Env:WZ_ASCIIDOCTOR_PATH;$Env:WZ_MSGMERGE_PATH;$Env:WZ_MSGFMT_PATH"
        echo "WZ_MINGW_ENV_PATH=$WZ_MINGW_ENV_PATH" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
    - name: Cache vcpkg dependencies
      uses: actions/cache@v5
      with:
        path: ${{env.WZ_VCPKG_BINARY_SOURCES_DIR}}
        key: ${{runner.os}}-${{matrix.compiler}}-${{matrix.arch}}-${{hashFiles('**/get-dependencies_win.ps1')}}-${{hashFiles('**/vcpkg.json')}}-${{hashFiles('**/.ci/vcpkg/**')}}
        restore-keys: |
          ${{runner.os}}-${{matrix.compiler}}-${{matrix.arch}}-${{hashFiles('**/get-dependencies_win.ps1')}}-${{hashFiles('**/vcpkg.json')}}
          ${{runner.os}}-${{matrix.compiler}}-${{matrix.arch}}-${{hashFiles('**/get-dependencies_win.ps1')}}-
    - name: Build vcpkg + dependencies
      shell: pwsh
      run: |
        $Env:PATH = "$Env:WZ_MINGW_ENV_PATH"
        & "$Env:WZ_POWERSHELL_PATH" .\src\get-dependencies_win.ps1 -VCPKG_BUILD_TYPE release
    - name: Clean vcpkg temp files
      shell: bash
      run: rm --recursive --force vcpkg/buildtrees
    - name: CMake Configure
      shell: pwsh
      run: |
        echo "::add-matcher::${{github.workspace}}/src/.github/log-matchers/cmake.json"
        $Env:PATH = "$Env:WZ_MINGW_ENV_PATH"
        & "$Env:WZ_CMAKE_PATH\cmake.exe" `
          -G Ninja `
          -S src `
          -B build `
          -D CMAKE_BUILD_TYPE=Release `
          -D CMAKE_TOOLCHAIN_FILE="$Env:GITHUB_WORKSPACE\vcpkg\scripts\buildsystems\vcpkg.cmake" `
          -D VCPKG_CHAINLOAD_TOOLCHAIN_FILE="$Env:GITHUB_WORKSPACE\src\.ci\cmake\toolchains\$Env:WZ_MINGW_PKG_PREFIX.cmake" `
          -D WZ_MINGW_DIST_PATH="$Env:WZ_MINGW_DIST_PATH" `
          -D WZ_DISTRIBUTOR="$Env:WZ_DISTRIBUTOR" `
          -D ENABLE_DISCORD=0 `
          -D DISCORD_RPC_APPID="need to use debugger breakpoint to find out" `
          -D ENABLE_GNS_NETWORK_BACKEND=1
        echo "::remove-matcher owner=cmake::"
    - name: CMake Build
      shell: pwsh
      run: |
        echo "::add-matcher::${{github.workspace}}/src/.github/log-matchers/${{matrix.compiler}}.json"
        & "$Env:WZ_CMAKE_PATH\cmake.exe" --build build --config Release --target warzone2100
        echo "::remove-matcher owner=${{matrix.compiler}}::"
    - name: CPack Zip
      shell: pwsh
      run: |
        & "$Env:WZ_CMAKE_PATH\cpack.exe" `
          -G ZIP `
          --config build\CPackConfig.cmake `
          -C Release `
          -D CPACK_PACKAGE_FILE_NAME=warzone2100 `
          -D CPACK_INCLUDE_TOPLEVEL_DIRECTORY=0 `
          -D CPACK_ARCHIVE_COMPONENT_INSTALL=1 `
          -D CPACK_COMPONENTS_ALL_IN_ONE_PACKAGE=1
        Move-Item -LiteralPath build\warzone2100.zip -Destination warzone2100-${{matrix.filename}}.zip
    - name: LS
      if: always()
      shell: bash
      run: ls -la; ls -la *
    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      if: success() && github.event_name != 'release' && matrix.publish_artifact
      with:
        name: warzone2100-${{matrix.filename}}
        path: ${{github.workspace}}\warzone2100-${{matrix.filename}}.zip
        archive: false # do not zip
        if-no-files-found: error
    - name: Upload Release
      if: success() && github.event_name == 'release' && matrix.deploy_release
      env:
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        GH_REPO: ${{github.repository}}
      shell: bash
      run: set -eu && gh release upload "$GITHUB_REF_NAME" warzone2100-${{matrix.filename}}.zip
