on:
  push:
  pull_request:
  release:
    types:
      - prereleased
      - released

jobs:
  windows-2025:
    runs-on: windows-2025 # https://github.com/actions/runner-images/tree/main/images/windows
    steps:
    - name: Dump Environment (pwsh)
      shell: pwsh
      run: echo $Env:PATH
    - name: Dump Environment (bash)
      shell: bash
      run: |
        set -eu
        uname -a
        mount
        echo ===============================================================================
        env | sort
        echo ===============================================================================
        IFS=: read -ra path <<< "$PATH"
        printf 'PATH=%s\n' "${path[@]}"
        for p in "${path[@]}"; do
          echo ===============================================================================
          echo $p
          ls -la "$p" || true
        done
  windows-2025-vs2026:
    runs-on: windows-2025-vs2026
    steps:
    - name: Dump Environment (pwsh)
      shell: pwsh
      run: echo $Env:PATH
    - name: Dump Environment (bash)
      shell: bash
      run: |
        set -eu
        uname -a
        mount
        echo ===============================================================================
        env | sort
        echo ===============================================================================
        IFS=: read -ra path <<< "$PATH"
        printf 'PATH=%s\n' "${path[@]}"
        for p in "${path[@]}"; do
          echo ===============================================================================
          echo $p
          ls -la "$p" || true
        done
